[features]
seeds = false
[programs.devnet]
solana_nft_rust = "62YCWSvxbc5yEnGLegtai4SV7rQ9NdEnS4MuTW4EfPd9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "my-solana-wallet/sell.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"
